Borrowed the cairo bit

diff --git a/bin/steps/cairo b/bin/steps/cairo
--- a/bin/steps/cairo
+++ b/bin/steps/cairo
@@ -1,39 +1,80 @@
-cd /tmp
-tar zxf pixman-0.30.2.tar.gz
-cd pixman-0.30.2/
-./configure --prefix=/app/vendor/pixman
-make -j4
-make install
-cd /app/vendor/pixman
-tar zcf /tmp/pixman-0.30.2-1.tar.gz .
-FreeType build/package:
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-cd /tmp
-tar jxf freetype-2.5.0.tar.bz2
-cd freetype-2.50.0/
-./configure --prefix=/app/vendor/freetype
-make -j4
-make install
-cd /app/vendor/freetype
-tar zcf /tmp/freetype-2.5.0-1.tar.gz .
-Cairo build/package:
+set -e # fail fast
 
-cd /tmp
-tar xf cairo-1.12.16.tar.xz
-cd cairo-1.12.16/
-PKG_CONFIG_PATH=/app/vendor/pixman/lib/pkgconfig:/app/vendor/freetype/lib/pkgconfig \
-  ./configure --prefix=/app/vendor/cairo
-make -j4
-make install
-cd /app/vendor/cairo
-tar zcf /tmp/cairo-1.12.16-1.tar.gz .
-giflib build/package:
+# parse params
+BUILD_DIR=$1
+CACHE_DIR=$2
+BUILDPACK_NAME=cairo
 
-cd /tmp
-tar jxf giflib-4.2.3.tar.bz2
-cd giflib-4.2.3/
-./configure --prefix=/app/vendor/giflib
-make -j4
-make -j4 install-exec install-data
-cd /app/vendor/giflib
-tar zcf /tmp/giflib-4.2.3-1.tar.gz .
+# use pigz if available for (potentially) faster decompression
+type pigz > /dev/null 2>&1 && alias tar='tar --use-compress-program=pigz'
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+function vendor() {
+  binary="$1"
+  path="$2"
+
+  echo "Fetching $binary" | indent
+  mkdir -p $path
+  curl $binary -s -o - | tar xz -C $path -f -
+
+  if [ -d "$path/bin" ]; then
+    export PATH=$path/bin:$PATH
+  fi
+
+  if [ -d "$path/lib/pkgconfig" ]; then
+    # pkg-config should handle compiler options (if used)
+    export PKG_CONFIG_PATH="$path/lib/pkgconfig:$PKG_CONFIG_PATH"
+  fi
+
+  # standard paths
+  export CPPPATH="$path/include:$CPPPATH"
+  export CPATH="$path/include:$CPATH"
+  export LIBRARY_PATH="$path/lib:$LIBRARY_PATH"
+
+  export LD_LIBRARY_PATH="$path/lib:$LD_LIBRARY_PATH"
+}
+
+echo "-----> Vendoring binaries"
+vendor "https://s3.amazonaws.com/mojodna-heroku/cairo-1.12.16-1.tar.gz"  "$BUILD_DIR/vendor/cairo"
+vendor "https://s3.amazonaws.com/mojodna-heroku/freetype-2.5.0-1.tar.gz" "$BUILD_DIR/vendor/freetype"
+vendor "https://s3.amazonaws.com/mojodna-heroku/giflib-4.2.3-1.tar.gz" "$BUILD_DIR/vendor/giflib"
+vendor "https://s3.amazonaws.com/mojodna-heroku/pixman-0.30.2-1.tar.gz"  "$BUILD_DIR/vendor/pixman"
+
+echo "-----> Tweaking Cairo, FreeType, and Pixman include paths"
+
+# node-canvas isn't using pkg-config, so we need to set non-standard paths
+export CPPPATH="$BUILD_DIR/vendor/cairo/include/cairo:$BUILD_DIR/vendor/pixman/include/pixman-1:$BUILD_DIR/vendor/freetype/include/freetype2:$CPPPATH"
+export CPATH="$BUILD_DIR/vendor/cairo/include/cairo:$BUILD_DIR/vendor/pixman/include/pixman-1:$BUILD_DIR/vendor/freetype/include/freetype2:$CPATH"
+
+echo "-----> Configuring build environment"
+
+cat <<EOF > export
+export PATH="$PATH:\$PATH"
+export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:$LD_LIBRARY_PATH"
+export LIBRARY_PATH="\$LIBRARY_PATH:$LIBRARY_PATH"
+export PKG_CONFIG_PATH="\$PKG_CONFIG_PATH:$PKG_CONFIG_PATH"
+export CPPPATH="\$CPPPATH:$CPPPATH"
+export CPATH="\$CPATH:$CPATH"
+EOF
+
+echo "-----> Building runtime environment"
+mkdir -p $BUILD_DIR/.profile.d
+
+cat <<EOF > $BUILD_DIR/.profile.d/$BUILDPACK_NAME.sh
+export PATH="${PATH//$BUILD_DIR//app}:\$PATH"
+export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:${LD_LIBRARY_PATH//$BUILD_DIR//app}"
+export LIBRARY_PATH="\$LIBRARY_PATH:${LIBRARY_PATH//$BUILD_DIR//app}"
+export PKG_CONFIG_PATH="\$PKG_CONFIG_PATH:${PKG_CONFIG_PATH//$BUILD_DIR//app}"
+export CPPPATH="\$CPPPATH:${CPPPATH//$BUILD_DIR//app}"
+export CPATH="\$CPATH:${CPATH//$BUILD_DIR//app}"
+EOF
